apiVersion: batch.yolo.ahilaly.dev/v1alpha1
kind: ChaosSimulation
metadata:
  name: chaos-simulation-cr
spec:
  level: 10 # 1 being the lowest and 10 the highest
  command: break my cluster networking layer (or at least try to)





